# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='question',
            new_name='questtext',
        ),
    ]
