# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0002_auto_20170127_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='questtext',
            new_name='quest_text',
        ),
    ]
