# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0003_auto_20170127_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Test_questions',
        ),
    ]
