# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testy', '0004_auto_20170127_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quest_text', models.TextField(verbose_name='Treść\xa0pytania')),
                ('answer1', models.TextField(verbose_name='Odpowiedź 1')),
                ('answer2', models.TextField(verbose_name='Odpowiedź 2')),
                ('answer3', models.TextField(verbose_name='Odpowiedź 3')),
                ('answer4', models.TextField(verbose_name='Odpowiedź 4')),
                ('corect', models.IntegerField(verbose_name='Poprawna jest odpowiedź nr:')),
            ],
        ),
        migrations.DeleteModel(
            name='Test_questions',
        ),
    ]
